modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
config = "matrixcraft.mixins.json"

[[mods]]
modId="matrixcraft"
version="1.0.0"
displayName="MatrixCraft"
description="Adds Matrix-style bullet trails and effects to TacZ guns"
authors="RaeYNCraft"

[[dependencies.matrixcraft]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.matrixcraft]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.matrixcraft]]
modId="tacz"
type="required"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"